version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: freqtrade_web_1
      APP_PORT: 8080

  web:
    image: freqtradeorg/freqtrade:stable
    restart: on-failure
    volumes:
      - "${APP_DATA_DIR}/app_data:/app_data"
      - "${APP_DATA_DIR}/user_data:/user_data"
    entrypoint: ["${APP_DATA_DIR}/entrypoint.sh"]
    command: trade