version: "2.3"

services:
  app_proxy:
    environment:
      APP_HOST: emby-server_web_1
      APP_PORT: 8097
      PROXY_AUTH_ADD: "false"

  web:
    image: emby/embyserver:4.8.10.0@sha256:be113ebc40cc354e4c0e9e551048c291dd2841661961d5fd796044213fd662cd
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/programdata:/config
      - ${APP_DATA_DIR}/tvshows:/mnt/share1
      - ${APP_DATA_DIR}/movies:/mnt/share2
